name: tests
on: [push, pull_request]
  
jobs:
  test:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Set up Environnement
        uses: BertSa/ActionJavaTest@v1
      - name: Run tests with Maven
        run: mvn -B test --file backend/pom.xml
  coverage:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Set up Environnement
        uses: BertSa/ActionJavaTest@v1
      - name: Run tests with Maven
        run: mvn clean verify --file backend/pom.xml
